---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ${DISTRO_NAME:-ubuntu-bionic}
    image: ${DISTRO_IMAGE:-ubuntu:bionic}

provisioner:
  name: ansible
  playbooks:
    prepare: ../specific-version/converge.yml
    converge: converge.yml
  env:
    DOCKER_COMPOSE_VERSION: "1.29.1"

verifier:
  name: ansible