---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: distro-image
    image: ${DISTRO_IMAGE:-ubuntu:bionic}

provisioner:
  name: ansible
  playbooks:
    prepare: ../default/converge.yml
    converge: converge.yml

verifier:
  name: ansible
