---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: distro-image
    image: ${DISTRO_IMAGE:-ubuntu:bionic}

provisioner:
  name: ansible
  log: true
  options:
    vvv: true

verifier:
  name: ansible