---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: distro-image
    image: ${MOLECULE_DISTRO:-ubuntu:bionic}
    env:
      SUDO_USER: "ubuntu"
      
provisioner:
  name: ansible
  log: true
  options:
    vvv: true

verifier:
  name: ansible